version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: hoteljb-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hoteljb
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
  app:
    build: .
    container_name: hoteljb-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hoteljb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      MULTIMEDIA_STORAGE_PATH: /uploads
    volumes:
      - ./multimedia-uploads:/uploads
volumes:
  mysql_data:
